// Auto-generated from posts/ directory
// Do not edit this file directly - edit the markdown files instead

import type { Post } from '../types'

export const posts: Post[] = [
  {
    "id": "getting-started",
    "title": "Getting Started with My Blog",
    "date": "2024-12-10T00:00:00.000Z",
    "tags": [
      "tutorial",
      "blog"
    ],
    "excerpt": "Learn how to use this blog framework and customize it to your needs.",
    "content": "# Getting Started\n\nWelcome to my blog! This is a simple blog framework built with React and Vite, inspired by Hexo.\n\n## Features\n\nThis blog framework includes:\n\n- Clean, minimal design\n- Responsive layout\n- Tag system for categorizing posts\n- Archive page for browsing by date\n- Project showcase section\n- Dark and light mode support\n\n## Getting Started\n\nTo add a new post, create a markdown file in the `posts/` directory:\n\n```bash\nnpm run new \"My New Post\"\n```\n\nEach post should have frontmatter with:\n- **title**: The post title\n- **date**: Publication date (YYYY-MM-DD format)\n- **tags**: Array of tag strings\n- **excerpt**: Short description for previews\n\n## Customization\n\nYou can customize the theme by editing the `_config.yml` file. The color scheme, fonts, and spacing can all be adjusted to match your personal style.\n\nHappy blogging!",
    "html": "<h1>Getting Started</h1>\n<p>Welcome to my blog! This is a simple blog framework built with React and Vite, inspired by Hexo.</p>\n<h2>Features</h2>\n<p>This blog framework includes:</p>\n<ul>\n<li>Clean, minimal design</li>\n<li>Responsive layout</li>\n<li>Tag system for categorizing posts</li>\n<li>Archive page for browsing by date</li>\n<li>Project showcase section</li>\n<li>Dark and light mode support</li>\n</ul>\n<h2>Getting Started</h2>\n<p>To add a new post, create a markdown file in the <code>posts/</code> directory:</p>\n<pre><code class=\"language-bash\">npm run new &quot;My New Post&quot;\n</code></pre>\n<p>Each post should have frontmatter with:</p>\n<ul>\n<li><strong>title</strong>: The post title</li>\n<li><strong>date</strong>: Publication date (YYYY-MM-DD format)</li>\n<li><strong>tags</strong>: Array of tag strings</li>\n<li><strong>excerpt</strong>: Short description for previews</li>\n</ul>\n<h2>Customization</h2>\n<p>You can customize the theme by editing the <code>_config.yml</code> file. The color scheme, fonts, and spacing can all be adjusted to match your personal style.</p>\n<p>Happy blogging!</p>\n"
  },
  {
    "id": "hello-world",
    "title": "Hello World",
    "date": "2024-12-08T00:00:00.000Z",
    "tags": [
      "introduction"
    ],
    "excerpt": "My first blog post. Welcome to my corner of the internet!",
    "content": "# Hello World\n\nHello, world! This is my first blog post.\n\n## About This Blog\n\nI created this blog to share my thoughts, projects, and learnings as a developer. Here you'll find:\n\n- Technical tutorials and guides\n- Project showcases and case studies\n- Thoughts on software development\n- Random musings and discoveries\n\n## Why Blogging?\n\nWriting helps me solidify my understanding of topics and hopefully helps others along the way. There's something special about putting thoughts into words and sharing them with the world.\n\n## What's Next?\n\nI'm planning to write about various topics including:\n\n- Web development techniques\n- Tool and library reviews\n- Personal projects and experiments\n- Career insights and tips\n\nStay tuned for more content!",
    "html": "<h1>Hello World</h1>\n<p>Hello, world! This is my first blog post.</p>\n<h2>About This Blog</h2>\n<p>I created this blog to share my thoughts, projects, and learnings as a developer. Here you&#39;ll find:</p>\n<ul>\n<li>Technical tutorials and guides</li>\n<li>Project showcases and case studies</li>\n<li>Thoughts on software development</li>\n<li>Random musings and discoveries</li>\n</ul>\n<h2>Why Blogging?</h2>\n<p>Writing helps me solidify my understanding of topics and hopefully helps others along the way. There&#39;s something special about putting thoughts into words and sharing them with the world.</p>\n<h2>What&#39;s Next?</h2>\n<p>I&#39;m planning to write about various topics including:</p>\n<ul>\n<li>Web development techniques</li>\n<li>Tool and library reviews</li>\n<li>Personal projects and experiments</li>\n<li>Career insights and tips</li>\n</ul>\n<p>Stay tuned for more content!</p>\n"
  },
  {
    "id": "react-hooks-guide",
    "title": "A Complete Guide to React Hooks",
    "date": "2024-12-05T00:00:00.000Z",
    "tags": [
      "react",
      "javascript",
      "tutorial"
    ],
    "excerpt": "Everything you need to know about React Hooks - useState, useEffect, and beyond.",
    "content": "# A Complete Guide to React Hooks\n\nReact Hooks revolutionized how we write React components. Let's dive deep into the most important hooks.\n\n## useState\n\nThe most basic hook for managing state in functional components.\n\n```javascript\nconst [count, setCount] = useState(0);\n```\n\n## useEffect\n\nHandle side effects like data fetching, subscriptions, or DOM manipulation.\n\n```javascript\nuseEffect(() => {\n  document.title = `Count: ${count}`;\n}, [count]);\n```\n\n## useContext\n\nAccess context values without wrapping components in Consumer.\n\n## useMemo and useCallback\n\nOptimize performance by memoizing values and functions.\n\n## Custom Hooks\n\nCreate reusable logic by extracting it into custom hooks:\n\n```javascript\nfunction useLocalStorage(key, initialValue) {\n  const [value, setValue] = useState(() => {\n    const saved = localStorage.getItem(key);\n    return saved ? JSON.parse(saved) : initialValue;\n  });\n\n  useEffect(() => {\n    localStorage.setItem(key, JSON.stringify(value));\n  }, [key, value]);\n\n  return [value, setValue];\n}\n```\n\nHooks make React development more intuitive and help keep code organized and reusable.",
    "html": "<h1>A Complete Guide to React Hooks</h1>\n<p>React Hooks revolutionized how we write React components. Let&#39;s dive deep into the most important hooks.</p>\n<h2>useState</h2>\n<p>The most basic hook for managing state in functional components.</p>\n<pre><code class=\"language-javascript\">const [count, setCount] = useState(0);\n</code></pre>\n<h2>useEffect</h2>\n<p>Handle side effects like data fetching, subscriptions, or DOM manipulation.</p>\n<pre><code class=\"language-javascript\">useEffect(() =&gt; {\n  document.title = `Count: ${count}`;\n}, [count]);\n</code></pre>\n<h2>useContext</h2>\n<p>Access context values without wrapping components in Consumer.</p>\n<h2>useMemo and useCallback</h2>\n<p>Optimize performance by memoizing values and functions.</p>\n<h2>Custom Hooks</h2>\n<p>Create reusable logic by extracting it into custom hooks:</p>\n<pre><code class=\"language-javascript\">function useLocalStorage(key, initialValue) {\n  const [value, setValue] = useState(() =&gt; {\n    const saved = localStorage.getItem(key);\n    return saved ? JSON.parse(saved) : initialValue;\n  });\n\n  useEffect(() =&gt; {\n    localStorage.setItem(key, JSON.stringify(value));\n  }, [key, value]);\n\n  return [value, setValue];\n}\n</code></pre>\n<p>Hooks make React development more intuitive and help keep code organized and reusable.</p>\n"
  }
]

export function getPostById(id: string): Post | undefined {
  return posts.find(post => post.id === id)
}

export function getPostsByTag(tag: string): Post[] {
  return posts.filter(post => post.tags && post.tags.includes(tag))
}

export function getAllTags(): Record<string, number> {
  const tagCount: Record<string, number> = {}
  posts.forEach(post => {
    if (post.tags) {
      post.tags.forEach(tag => {
        tagCount[tag] = (tagCount[tag] || 0) + 1
      })
    }
  })
  return tagCount
}

export function getPostsByYear(): Record<string, Post[]> {
  const byYear: Record<string, Post[]> = {}
  posts.forEach(post => {
    const year = post.date ? post.date.split('-')[0] : 'Unknown'
    if (!byYear[year]) byYear[year] = []
    byYear[year].push(post)
  })
  Object.keys(byYear).forEach(year => {
    byYear[year].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
  })
  return byYear
}
